import { defineConfig, devices } from "@playwright/test";

/**
 * Playwright Test Configuration
 * Generated by cc-e2e
 *
 * Note: Authentication settings will be configured by /e2e:init based on project analysis.
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  // Test directory includes generated cc-e2e specs and hand-written canvas smoke specs.
  testDir: ".",
  testMatch: ["playwright-tests/tests/**/*.ts", "tests/e2e/**/*.spec.ts"],

  // Run tests in parallel
  fullyParallel: true,

  // Fail the build on CI if you accidentally left test.only in the source code
  forbidOnly: !!process.env.CI,

  // Retry on CI only
  retries: process.env.CI ? 2 : 0,

  // Limit parallel workers on CI
  workers: process.env.CI ? 1 : undefined,

  // Reporter configuration
  reporter: [["html", { open: "never" }], ["list"]],

  // Shared settings for all projects
  use: {
    // Base URL for navigation
    baseURL: "http://127.0.0.1:3100",

    // Collect trace when retrying the failed test
    trace: "on-first-retry",

    // Capture screenshot on failure
    screenshot: "only-on-failure",
  },

  // Global setup
  globalSetup: "./playwright-tests/global-setup.ts",

  // Browser projects
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
    },
  ],

  // Web server configuration
  // NOTE: Set reuseExistingServer to true for local development
  // The server will NOT be auto-started if already running
  webServer: {
    command: "pnpm --dir apps/web exec next dev -p 3100",
    url: "http://127.0.0.1:3100",
    reuseExistingServer: !process.env.CI,
    timeout: 120 * 1000,
  },
});
