// Re-export pure constants from @zseven-w/pen-core
export {
  MIN_ZOOM,
  MAX_ZOOM,
  ZOOM_STEP,
  SNAP_THRESHOLD,
  DEFAULT_FILL,
  DEFAULT_STROKE,
  DEFAULT_STROKE_WIDTH,
  CANVAS_BACKGROUND_LIGHT,
  CANVAS_BACKGROUND_DARK,
  SELECTION_BLUE,
  COMPONENT_COLOR,
  INSTANCE_COLOR,
  HOVER_BLUE,
  HOVER_LINE_WIDTH,
  HOVER_DASH,
  INDICATOR_BLUE,
  INDICATOR_LINE_WIDTH,
  INDICATOR_DASH,
  INDICATOR_ENDPOINT_RADIUS,
  FRAME_LABEL_FONT_SIZE,
  FRAME_LABEL_OFFSET_Y,
  FRAME_LABEL_COLOR,
  PEN_ANCHOR_FILL,
  PEN_ANCHOR_RADIUS,
  PEN_ANCHOR_FIRST_RADIUS,
  PEN_HANDLE_DOT_RADIUS,
  PEN_HANDLE_LINE_STROKE,
  PEN_RUBBER_BAND_STROKE,
  PEN_RUBBER_BAND_DASH,
  PEN_CLOSE_HIT_THRESHOLD,
  DIMENSION_LABEL_OFFSET_Y,
  DEFAULT_FRAME_FILL,
  DEFAULT_TEXT_FILL,
  GUIDE_COLOR,
  GUIDE_LINE_WIDTH,
  GUIDE_DASH,
} from '@zseven-w/pen-core';

import { CANVAS_BACKGROUND_LIGHT, CANVAS_BACKGROUND_DARK } from '@zseven-w/pen-core';

// Browser-only function — not in pen-core
export function getCanvasBackground(): string {
  if (typeof document === 'undefined') return CANVAS_BACKGROUND_DARK;
  return document.documentElement.classList.contains('light')
    ? CANVAS_BACKGROUND_LIGHT
    : CANVAS_BACKGROUND_DARK;
}
