//! Message types — core message union, ContentBlock, Header with DAG linking.
//!
//! Every message carries a Header that records its UUID, timestamp, and an
//! optional pointer back to a parent message UUID, enabling a directed acyclic
//! graph (DAG) of conversation history.

const std = @import("std");
const json = @import("json.zig");
const uuid_mod = @import("uuid.zig");

pub const Uuid = uuid_mod.Uuid;
pub const JsonValue = json.JsonValue;

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

/// Metadata attached to every message.
///
/// `uuid`              — unique identifier for this message.
/// `timestamp`         — Unix epoch in milliseconds (UTC).
/// `parent_uuid`       — UUID of the message this one replies to (DAG edge).
/// `parent_tool_use_id`— when this message is a tool result, the originating
///                       tool-use block id.
pub const Header = struct {
    uuid: Uuid,
    timestamp: i64,
    parent_uuid: ?Uuid = null,
    parent_tool_use_id: ?[]const u8 = null,

    /// Create a fresh Header with a new UUID v4 and the current wall-clock time.
    pub fn init() Header {
        return .{
            .uuid = uuid_mod.v4(),
            .timestamp = std.time.milliTimestamp(),
        };
    }

    /// Create a Header that records `parent` as its DAG predecessor.
    pub fn withParent(parent: Uuid) Header {
        var h = init();
        h.parent_uuid = parent;
        return h;
    }
};

// ---------------------------------------------------------------------------
// ContentBlock sub-types
// ---------------------------------------------------------------------------

/// An image carried inline in a message.
pub const ImageBlock = struct {
    /// URL, data-URI, or file path identifying the image.
    source: []const u8,
    /// MIME type, e.g. "image/png".
    media_type: []const u8,
};

/// A request to invoke a named tool.
pub const ToolUseBlock = struct {
    /// Opaque identifier that pairs this request with its result.
    id: []const u8,
    /// Registered name of the tool to call.
    name: []const u8,
    /// Validated input arguments as a JSON value.
    input: JsonValue,
};

/// The result returned after a tool invocation.
pub const ToolResultBlock = struct {
    /// Matches the `id` field of the corresponding `ToolUseBlock`.
    tool_use_id: []const u8,
    /// Serialisable output (or error payload) from the tool.
    content: JsonValue,
    /// `true` when the tool execution itself failed.
    is_error: bool = false,
};

/// Extended reasoning / chain-of-thought emitted by the model.
pub const ThinkingBlock = struct {
    thinking: []const u8,
};

// ---------------------------------------------------------------------------
// ContentBlock
// ---------------------------------------------------------------------------

/// A tagged union representing one piece of content inside a message.
pub const ContentBlock = union(enum) {
    text: []const u8,
    image: ImageBlock,
    tool_use: ToolUseBlock,
    tool_result: ToolResultBlock,
    thinking: ThinkingBlock,
};

// ---------------------------------------------------------------------------
// Message variants
// ---------------------------------------------------------------------------

/// Subtypes for `SystemMessage` that further classify its role.
pub const SystemSubtype = enum {
    local_command,
    compact_boundary,
    status,
};

/// A message authored by the human (or the harness acting on their behalf).
pub const UserMessage = struct {
    header: Header,
    content: []const ContentBlock,
    /// When `true` this message carries harness-internal bookkeeping rather
    /// than user-visible text.
    is_meta: bool = false,
};

/// A response generated by the AI assistant.
pub const AssistantMessage = struct {
    header: Header,
    content: []const ContentBlock,
    /// The reason the model stopped generating (e.g. "end_turn", "max_tokens").
    stop_reason: ?[]const u8 = null,
    /// Estimated cost in USD for this completion, if available.
    cost: ?f64 = null,
};

/// A system-level notification injected by the harness.
pub const SystemMessage = struct {
    header: Header,
    content: []const u8,
    subtype: ?SystemSubtype = null,
};

/// Streaming progress update tied to an in-flight tool-use block.
pub const ProgressMessage = struct {
    header: Header,
    tool_use_id: []const u8,
    data: JsonValue,
};

/// A logical deletion marker — indicates that a prior message has been
/// superseded or redacted without removing it from the store.
pub const TombstoneMessage = struct {
    header: Header,
};

// ---------------------------------------------------------------------------
// Message
// ---------------------------------------------------------------------------

/// Top-level tagged union covering every kind of message in the conversation.
pub const Message = union(enum) {
    user: UserMessage,
    assistant: AssistantMessage,
    system: SystemMessage,
    progress: ProgressMessage,
    tombstone: TombstoneMessage,

    /// Return the Header regardless of which variant is active.
    pub fn getHeader(self: Message) Header {
        return switch (self) {
            inline else => |m| m.header,
        };
    }
};

// ---------------------------------------------------------------------------
// MessageStore
// ---------------------------------------------------------------------------

/// An ordered, append-only store for `Message` values.
///
/// Backed by an arena so every string / slice referenced from stored messages
/// is freed in one shot on `deinit`. Callers must allocate message `content`
/// slices and their inner strings through `allocator()` (or dupe borrowed data
/// into it) — anything else risks use-after-free on deinit.
pub const MessageStore = struct {
    arena: std.heap.ArenaAllocator,
    messages: std.ArrayListUnmanaged(Message),

    pub fn init(gpa: std.mem.Allocator) MessageStore {
        return .{
            .arena = std.heap.ArenaAllocator.init(gpa),
            .messages = .{},
        };
    }

    pub fn deinit(self: *MessageStore) void {
        self.messages.deinit(self.arena.child_allocator);
        self.arena.deinit();
    }

    /// Allocator whose lifetime matches the store — use this for any
    /// content/string owned by a stored message.
    pub fn allocator(self: *MessageStore) std.mem.Allocator {
        return self.arena.allocator();
    }

    /// Append a message to the store.
    pub fn append(self: *MessageStore, msg: Message) !void {
        try self.messages.append(self.arena.child_allocator, msg);
    }

    /// Return the number of messages currently held.
    pub fn count(self: *const MessageStore) usize {
        return self.messages.items.len;
    }

    /// Direct slice access to all stored messages.
    pub fn items(self: *const MessageStore) []const Message {
        return self.messages.items;
    }
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

test "Header init generates UUID" {
    const h = Header.init();

    // Dashes at canonical UUID positions
    try std.testing.expectEqual('-', h.uuid[8]);
    try std.testing.expectEqual('-', h.uuid[13]);
    try std.testing.expectEqual('-', h.uuid[18]);
    try std.testing.expectEqual('-', h.uuid[23]);

    // Version nibble must be '4'
    try std.testing.expectEqual('4', h.uuid[14]);

    // Timestamp must be positive (we are well past the epoch)
    try std.testing.expect(h.timestamp > 0);

    // No parent by default
    try std.testing.expectEqual(@as(?Uuid, null), h.parent_uuid);
}

test "Header withParent links to parent" {
    const parent_header = Header.init();
    const child_header = Header.withParent(parent_header.uuid);

    // The child must record the parent's UUID
    try std.testing.expect(child_header.parent_uuid != null);
    try std.testing.expect(uuid_mod.eql(child_header.parent_uuid.?, parent_header.uuid));

    // Child must have its own distinct UUID
    try std.testing.expect(!uuid_mod.eql(child_header.uuid, parent_header.uuid));
}

test "Message union getHeader" {
    const msg = Message{ .system = SystemMessage{
        .header = Header.init(),
        .content = "agent started",
        .subtype = .status,
    } };

    const h = msg.getHeader();

    // Version nibble must be '4'
    try std.testing.expectEqual('4', h.uuid[14]);
    try std.testing.expect(h.timestamp > 0);
}

test "MessageStore append and count" {
    const allocator = std.testing.allocator;

    var store = MessageStore.init(allocator);
    defer store.deinit();

    try std.testing.expectEqual(@as(usize, 0), store.count());

    const msg = Message{ .tombstone = TombstoneMessage{
        .header = Header.init(),
    } };
    try store.append(msg);

    try std.testing.expectEqual(@as(usize, 1), store.count());
}

test "MessageStore items returns all messages" {
    const allocator = std.testing.allocator;
    var store = MessageStore.init(allocator);
    defer store.deinit();

    try store.append(.{ .system = .{ .header = Header.init(), .content = "sys" } });
    try store.append(.{ .tombstone = .{ .header = Header.init() } });
    try store.append(.{ .system = .{ .header = Header.init(), .content = "sys2" } });

    const items = store.items();
    try std.testing.expectEqual(@as(usize, 3), items.len);
    try std.testing.expectEqualStrings("sys", items[0].system.content);
    try std.testing.expectEqualStrings("sys2", items[2].system.content);
}

test "MessageStore allocator returns arena allocator" {
    const allocator = std.testing.allocator;
    var store = MessageStore.init(allocator);
    defer store.deinit();

    // Use the store's arena allocator to create content
    const arena_alloc = store.allocator();
    const text = try arena_alloc.dupe(u8, "hello from arena");
    const content = try arena_alloc.alloc(ContentBlock, 1);
    content[0] = .{ .text = text };

    try store.append(.{ .user = .{
        .header = Header.init(),
        .content = content,
    } });

    const items = store.items();
    try std.testing.expectEqual(@as(usize, 1), items.len);
    try std.testing.expectEqualStrings("hello from arena", items[0].user.content[0].text);
}

test "Header parent_tool_use_id" {
    var h = Header.init();
    try std.testing.expectEqual(@as(?[]const u8, null), h.parent_tool_use_id);
    h.parent_tool_use_id = "toolu_abc123";
    try std.testing.expectEqualStrings("toolu_abc123", h.parent_tool_use_id.?);
}

test "Message getHeader works for all variants" {
    const user_msg = Message{ .user = .{
        .header = Header.init(),
        .content = &.{},
    } };
    const assistant_msg = Message{ .assistant = .{
        .header = Header.init(),
        .content = &.{},
    } };
    const progress_msg = Message{ .progress = .{
        .header = Header.init(),
        .tool_use_id = "t1",
        .data = .null,
    } };

    // All variants should return valid headers
    try std.testing.expect(user_msg.getHeader().timestamp > 0);
    try std.testing.expect(assistant_msg.getHeader().timestamp > 0);
    try std.testing.expect(progress_msg.getHeader().timestamp > 0);

    // Each should have its own UUID
    try std.testing.expect(!uuid_mod.eql(user_msg.getHeader().uuid, assistant_msg.getHeader().uuid));
}
