// Re-export from @zseven-w/pen-core — the canonical source
export {
  DEFAULT_FRAME_ID,
  DEFAULT_PAGE_ID,
  createEmptyDocument,
  getActivePage,
  getActivePageChildren,
  setActivePageChildren,
  getAllChildren,
  migrateToPages,
  ensureDocumentNodeIds,
  findNodeInTree,
  findParentInTree,
  removeNodeFromTree,
  updateNodeInTree,
  flattenNodes,
  insertNodeInTree,
  isDescendantOf,
  getNodeBounds,
  findClearX,
  scaleChildrenInPlace,
  rotateChildrenInPlace,
  deepCloneNode,
  cloneNodeWithNewIds,
  cloneNodesWithNewIds,
} from '@zseven-w/pen-core';
