import type { BuiltinProviderPreset } from "@cucumber/shared";

/**
 * Built-in provider presets — common AI providers with their default API endpoints.
 * Users can add any of these by providing their API key.
 */
export const BUILTIN_PROVIDER_PRESETS: BuiltinProviderPreset[] = [
  {
    id: "openai",
    label: "OpenAI",
    type: "openai",
    baseURL: "https://api.openai.com/v1",
    regions: ["global"],
    placeholder: "sk-...",
    modelPlaceholder: "gpt-4o",
  },
  {
    id: "anthropic",
    label: "Anthropic",
    type: "anthropic",
    baseURL: "https://api.anthropic.com/v1",
    regions: ["global"],
    placeholder: "sk-ant-...",
    modelPlaceholder: "claude-sonnet-4-6",
  },
  {
    id: "google",
    label: "Google AI",
    type: "google",
    baseURL: "https://generativelanguage.googleapis.com/v1beta",
    regions: ["global"],
    placeholder: "AIza...",
    modelPlaceholder: "gemini-2.5-flash",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    type: "deepseek",
    baseURL: "https://api.deepseek.com/v1",
    regions: ["global", "cn"],
    placeholder: "sk-...",
    modelPlaceholder: "deepseek-chat",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    type: "openai-compat",
    baseURL: "https://openrouter.ai/api/v1",
    regions: ["global"],
    placeholder: "sk-or-...",
    modelPlaceholder: "openai/gpt-4o",
  },
  {
    id: "zhipu",
    label: "智谱 GLM",
    type: "openai-compat",
    baseURL: "https://open.bigmodel.cn/api/paas/v4",
    regions: ["cn"],
    placeholder: "...",
    modelPlaceholder: "glm-4-plus",
  },
  {
    id: "kimi",
    label: "Kimi (月之暗面)",
    type: "openai-compat",
    baseURL: "https://api.moonshot.cn/v1",
    regions: ["cn"],
    placeholder: "sk-...",
    modelPlaceholder: "moonshot-v1-8k",
  },
  {
    id: "bailian",
    label: "阿里百炼",
    type: "openai-compat",
    baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    regions: ["cn"],
    placeholder: "sk-...",
    modelPlaceholder: "qwen-plus",
  },
  {
    id: "doubao",
    label: "豆包 (字节)",
    type: "openai-compat",
    baseURL: "https://ark.cn-beijing.volces.com/api/v3",
    regions: ["cn"],
    placeholder: "...",
    modelPlaceholder: "doubao-pro-256k",
  },
  {
    id: "custom",
    label: "Custom (OpenAI-compatible)",
    type: "openai-compat",
    baseURL: "",
    altBaseURL: "",
    regions: ["global"],
    placeholder: "sk-...",
    modelPlaceholder: "model-name",
  },
];
